use_frameworks!

target 'CHDayPicker_Example' do
  pod 'CHDayPicker', :path => '../'

  target 'CHDayPicker_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
